### ISSUE TITLE
(OUI Next Theme) Alerting

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/alerting-dashboards-plugin#663]
_This issue to be transferred to corresponding repository_

I am working on launching new light and dark mode themes provided by [OUI component library](https://oui.opensearch.org/1.2/#/) for a target launch within 2.10. These changes support the vision expressed in [Future Vision for Dashboards](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4298.)

I have identified the following front end related issues that prevent the theme from appearing complete and potential solutions within this feature:

**Global**
- [x] Duplicate breadcrumb appears on page. Breadcrumb should appear within EuiHeader. 

**Create Monitor flow**
- [x] Query section: empty state (before a user selects an index) appears with a border with a manually set color value. In dark mode, this appears as a bright-white border. 
      - Resolution Option 1 (best): To align to best practices, [EuiEmptyPrompt](https://oui.opensearch.org/1.2/#/display/empty-prompt) should be used for empty states.
      - Resolution Option 2 (ok for short term): Remove hard coded color value in favor of using sass variable $ouiColorLightShade that will adjust appropriately across light and dark mode
      
<img width="1231" alt="Screen Shot 2023-07-25 at 2 31 50 PM" src="https://github.com/opensearch-project/oui/assets/105819041/c7f6f861-b74f-4f79-9ca8-0e83f97cb2cd">

      
- [x] Trigger section: Empty state "loading destinations" appears on a background with a manually set background color value. In dark mode, this appears as a bright-white background and the text is not legible. 
      - Resolution Option 1 (best): To align to best practices, [EuiEmptyPrompt](https://oui.opensearch.org/1.2/#/display/empty-prompt#loading-and-error-prompts) should be used for empty loading state 
      - Resolution Option 2 (ok for short term): Remove background 

<img width="1232" alt="Screen Shot 2023-07-25 at 2 32 03 PM" src="https://github.com/opensearch-project/oui/assets/105819041/4a08da83-3dcf-4c48-b81c-0607c277b73e">

- [x] "Monitor defining method", "You can add up to 9 more triggers.": Description text is set to extra small. This is creating contrast issues and a11y tests fail. The minimum description text size should be `m`. Only in special cases should `s` and `xs` should be used.
